### ISSUE TITLE
Unable to change the number of vCPU's

### ISSUE THREAD

**Issue by dlintott** [OpenXenManager/openxenmanager#10]
Trying to change the number of vCPU's displays the follow message in console and does not alter the number of vCPU's
```
{'Status': 'Failure', 'ErrorDescription': ['INVALID_VALUE', u'VCPU values must satisfy: 0 < VCPUs_at_startup \u2264 VCPUs_max', '2']}
```
See also: https://sourceforge.net/p/openxenmanager/bugs/13/

**Comment by dcarnelutti** [comment]
any news about this issue? im using xenserver 7.0 and got the same problem

**Comment by pharazon** [comment]
I'm also having the same problem on Xen Center 6.2 (XenServer 6.2.0-70446c). I'm using
openxenmanager:all/trusty 0.r80+dfsg-4 uptodate
