### ISSUE TITLE
Installing on Mac OS (Any Version)

### ISSUE THREAD

**Issue by sant0ro** [OpenXenManager/openxenmanager#107]
Hello due the dudes, i created this issue like a tutorial for installing openxenmanager in OS X (including El Capitan)

1. Installing Homebrew
Open Terminal, and write:

`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

2. Update Home Brew
`brew upgrade && brew update`

3. Install Python and Python GTK in Home Brew
`brew install python`
`brew install pygtk`

4. Installing FLTK
`brew install --devel https://raw.githubusercontent.com/Homebrew/homebrew/master/Library/Formula/fltk.rb`

5. Installing Tiger-VNC and Forcing omitting the FLTK dependency (Without omitting Brew will say that is an incompatible formulae)
`brew install https://gist.githubusercontent.com/sant0ro/ea059a11852878b843f9/raw/279892edd1d93f4850c5aba0bcc3242db2ec8b00/tiger-vnc.rb`

6. After all Done Download The Last **OpenXenManager** Source Code

7. Open the Terminal and go to the directory 
`cd yourdownloadeddir`

8. Now Build OpenXenManager
`python setup.py build`

9. Install OpenXenManager
`python setup.py install`

10. Run The OpenXenManager by First Time (Opening the .sh) after Loaded Close it

11. Open the file oxc.conf by Opening Finder and Command + G
`~/.config/openxenmanager/`

12. Edit the file changing the `[options]` line to this:
`[options]
`
`vnc_viewer = /usr/local/bin/vncviewer`

13. Save it and Open OpenXenManager and Everything will Work.

Obs.: If something here is wrong, correct me. Also if my english/explanation is bad, feel free to correct me.

Cheers,

**Comment by dlintott** [comment]
@sant0ro Many thanks, I shall have to add this to wiki/readme

**Comment by sant0ro** [comment]
Thanks, closing as the owner readed the issue.

**Comment by steakknife** [comment]
#### Errata 
1. tiger-vnc brew formula was incompatible with modern GnuTLS. **Fix:** `brew install https://gist.githubusercontent.com/steakknife/064302dc55e76231d612/raw/tiger-vnc.rb`
2. ConfigObj was missing. **Fix:** `pip install configobj`

Otherwise, seems to work! :cake:

**Comment by ellingtonb** [comment]
**If someone is having an error while exiting the tool like below:**
`/openxenmanager:37: GtkWarning: Attempting to store changes into /Users/xxxx/.local/share/recently-used.xbel', but failed: Datei »/Users/xxxx/.local/share/recently-used.xbel.PJNHEY« konnte nicht angelegt werden:
  gtk.main()
./openxenmanager:37: GtkWarning: Attempting to set the permissions of /Users/xxxx/.local/share/recently-used.xbel', but failed:
  gtk.main()
Exiting...`

**let’s write this line in the console/terminal to fix:**
`mkdir -p ~/.local/share`

**It works for me!**

**Comment by marcelocecin** [comment]
3. Installing FLTK
brew install --devel https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/fltk.rb

**Comment by sant0ro** [comment]
@marcelocecin you need instal pygtk! Please follow entirely my tutorial.

**Comment by marcelocecin** [comment]
@sant0ro here's my screen shot
![captura de tela 2016-08-11 as 11 54 55](https://cloud.githubusercontent.com/assets/2955762/17592910/8615ec02-5fba-11e6-9569-4bf55def2093.png)

**Comment by sant0ro** [comment]
@marcelocecin you need those dependencies.

**Comment by marcelocecin** [comment]
I have to run this command: sudo xcode-select -switch /Applications/Xcode-beta.app/Contents/Developer/

**Comment by jfberry** [comment]
Falls down at FLTK step

Jamess-MBP-7:~ berryj$ brew install --devel https://raw.githubusercontent.com/Homebrew/homebrew/master/Library/Formula/fltk.rb

curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl --fail --progress-bar --remote-time --location --user-agent Homebrew/0.9.9\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.11.6)\ curl/7.43.0 https://raw.githubusercontent.com/Homebrew/homebrew/master/Library/Formula/fltk.rb -o /Users/berryj/Library/Caches/Homebrew/Formula/fltk.rb

**Comment by sant0ro** [comment]
@jfberry now will work.
I edited the main post.

**Comment by jfberry** [comment]
@sant0ro thanks, that worked. Now I notice that I need to do: brew install Caskroom/cask/xquartz before tiger-vnc

**Comment by sant0ro** [comment]
@jfberry glad to know that is working for you ;)

**Comment by roberthurricane** [comment]
Thanks for the guide. After updating my homebrew however, it is failing to install the first package listed:

jin:~ robert$ brew install caskroom
Error: No available formula with the name "caskroom"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

**Comment by sant0ro** [comment]
@roberthurricane skip Caskroom, by default new Homebrew's already have it.

**Comment by krydm** [comment]
@sant0ro, many thanks, first of all. Secondly, I'm getting the same error as @marcelocecin:

>./openxenmanager
Traceback (most recent call last):
  File "./openxenmanager", line 23, in <module>
    import gtk
ImportError: No module named gtk

Pygtk is installed, though:
>brew info pygtk
pygtk: stable 2.24.0 (bottled)
GTK+ bindings for Python
http://www.pygtk.org/
/usr/local/Cellar/pygtk/2.24.0_1 (590 files, 15.4M) *
  Poured from bottle on 2016-09-20 at 10:41:18
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pygtk.rb
==> Dependencies
Build: pkg-config ✔
Required: glib ✔, gtk+ ✔, atk ✔, pygobject ✔, py2cairo ✔
Optional: libglade ✘
==> Options
--universal
	Build a universal binary
--with-libglade
	Build with libglade support

Just in case: not sure what is the relation between these two, but here is the gtk info:
>brew info gtk
gtk+: stable 2.24.31 (bottled), HEAD
GUI toolkit
http://gtk.org/
/usr/local/Cellar/gtk+/2.24.31 (1,198 files, 53.0M) *
  Poured from bottle on 2016-09-20 at 10:41:11
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gtk+.rb
==> Dependencies
Build: xz ✔, pkg-config ✔
Required: gdk-pixbuf ✔, atk ✔, pango ✔, gobject-introspection ✔, hicolor-icon-theme ✔
Optional: jasper ✘
==> Options
--universal
	Build a universal binary
--with-jasper
	Build with jasper support
--with-quartz-relocation
	Build with quartz relocation support
--HEAD
	Install HEAD version

**Comment by sant0ro** [comment]
@krydm weird, you already have pygtk and gtk, try restart your machine.

**Comment by krydm** [comment]
@sant0ro just tried, didn't help :(

**Comment by sant0ro** [comment]
@krydm remember to install PyGTK. You only have GTK and Python.

**Comment by hyperized** [comment]
Omitting `brew install caskroom` and doing this for FLTK instead `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/fltk.rb` (no longer devel?) did miracles for me.

**Comment by sant0ro** [comment]
Updated main answer. with the Instructions of @hyperized

**Comment by guidoilbaldo** [comment]
Hi,

followed your brilliant tutorial and managed to install openxenmanager and connect it to a XEN cluster.
Still, I'm experiencing issues when clicking to create a new VM.
I get this error:
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window_menuitem.py", line 795, in on_m_newvm_activate
    self.xc_servers[self.selected_host].fill_list_phydvd(self.listphydvd)
  File "/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER_menuitem.py", line 297, in fill_list_phydvd
    and self.all['SR'][sr]['sm_config']["type"] == "cd":
KeyError: 'type'`

Please let me know how to fix this!

**Comment by sant0ro** [comment]
@guidoilbaldo maybe this be a OpenXenManager Issue. Not related to my tutorial.

The problem of OpenXenManager it'd that the author stopped commiting. So any bugs would not be fixed or corrected.

Sadlt OpenXenManager it's the onliest software that allows manage Xen by non-Windows Environments.

I would recommend you using XenOrchestra that is a Web Interface Management for Xen.

**Comment by dlintott** [comment]
Hi @sant0ro and all

Apologies for the lack of activity here... I am still about, and continue to recieve all the notifications about OpenXenManager. Unfortunately time hasn't been on my side recently, but intend to get back to working on OpenXenManager very soon.

**Comment by sant0ro** [comment]
@dlintott we know how time is it hahaha.

Anyways, maybe some day you get time to do the updates.

Anyways, OpenXenManager is good, but very very buggy. xD

**Comment by marcelocecin** [comment]
brew doctor
brew cask reinstall xquartz
but still with the error: No module named gtk
![captura de tela 2017-05-29 as 17 22 11](https://cloud.githubusercontent.com/assets/2955762/26561322/c01fb8f6-4493-11e7-8551-5c620f88ce72.png)
![captura de tela 2017-05-29 as 17 23 47](https://cloud.githubusercontent.com/assets/2955762/26561330/c8b0256e-4493-11e7-872e-351a21fffe4a.png)

**Comment by barciella** [comment]
Plenty of errors I got was because I had anaconda and brew python at the same type. Plugins would install in conda instead of brew python. After I completely removed anaconda with their clean uninstall and installed the pre-requisites again with brew and pip everything worked.

**Comment by josep112** [comment]
I followed all the steps above but my monitor does not work, I had no errors in the installation what can it be?

**Comment by vpakg** [comment]
Perfect, works well. The only difference is that I didn't have an .sh file, I had to run `python openxenmanager` instead. 

Great tutorial, Obrigado!

**Comment by LtDan33** [comment]
Thanks for the info, very helpful. Please note I had to run `brew cask install xquartz` to get xquartz

**Comment by ksachdeva11** [comment]
I have gtk installed still getting the below error.
`BLDM2558-MAC:openxenmanager-master ksachdeva$ python openxenmanager
Traceback (most recent call last):
  File "openxenmanager", line 23, in <module>
    import gtk
ImportError: No module named gtk
BLDM2558-MAC:openxenmanager-master`

**Comment by audricd** [comment]
worked like a charm.. setting custom VNC did the trick. Otherwise, its almost a useless GUI management tool! Thank you so much!

**Comment by OMK1670** [comment]
Can any one help for this issue on Mac OS BIg sure
admins-MacBook-Pro openxenmanager % sudo /usr/local/bin/openxenmanager
Password:
Traceback (most recent call last):
  File "/usr/local/bin/openxenmanager", line 4, in <module>
    __import__('pkg_resources').run_script('openxenmanager==0.1b1', 'openxenmanager')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/EGG-INFO/scripts/openxenmanager", line 23, in <module>
    import gtk
ImportError: No module named gtk
@admins-MacBook-Pro openxenmanager % 

We installed gtk using brew but here expecting from pip2.7 So not getting the fix for this

@admins-MacBook-Pro openxenmanager % python -m pip install gtk                           
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement gtk (from versions: none)
ERROR: No matching distribution found for gtk

**Comment by choiysr** [comment]
can not install
brew install pygtk
brew install https://gist.githubusercontent.com/steakknife/064302dc55e76231d612/raw/tiger-vnc.rb

**Comment by olivierlambert** [comment]
@choiysr this project is not maintained anymore (no major update since 2016). I would suggest to use Xen Orchestra or any supported client for XCP-ng/Citrix Hypervisor. If you are using XCP-ng, you'll have a bundled web client very soon, called XO Lite.
