### ISSUE TITLE
Got error when running openxenmanager on Fedora27

### ISSUE THREAD

**Issue by classloader** [OpenXenManager/openxenmanager#142]
No protocol specified
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: Warning: invalid (NULL) pointer instance
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: GtkWarning: IA__gdk_pango_context_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: PangoWarning: pango_context_set_font_description: assertion 'context != NULL' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: PangoWarning: pango_context_set_base_dir: assertion 'context != NULL' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: PangoWarning: pango_context_set_language: assertion 'context != NULL' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: PangoWarning: pango_layout_new: assertion 'context != NULL' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: PangoWarning: pango_layout_set_attributes: assertion 'layout != NULL' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: PangoWarning: pango_layout_set_text: assertion 'layout != NULL' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: PangoWarning: pango_layout_get_unknown_glyphs_count: assertion 'PANGO_IS_LAYOUT (layout)' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: GtkWarning: IA__gdk_screen_get_display: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: GtkWarning: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: GtkWarning: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: GtkWarning: IA__gdk_colormap_alloc_colors: assertion 'GDK_IS_COLORMAP (colormap)' failed
  self.builder.add_from_file(g_file)
/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:192: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
  self.builder.add_from_file(g_file)
While loading Glade GUI Builder file "/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/ui/master_password.glade" a duplicate entry was found:
Traceback (most recent call last):
  File "./openxenmanager", line 36, in <module>
    wine = oxcWindow()
  File "/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py", line 192, in __init__
    self.builder.add_from_file(g_file)
glib.GError: Could not parse color `#ffff00000000'
Exiting...

**Comment by classloader** [comment]
start success after reboot system.

**Comment by pgnzbl** [comment]
I also encountered the same problem. After restarting the system（sudo reboot）, the problem still exists

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
window.py:184: Warning: invalid (NULL) pointer instance
  self.builder.add_from_file(self.gladefile)
window.py:184: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: GtkWarning: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: GtkWarning: gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: Warning: value "TRUE" of type 'gboolean' is invalid or out of range for property 'visible' of type 'gboolean'
  self.builder.add_from_file(self.gladefile)
window.py:184: GtkWarning: gdk_pango_context_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: PangoWarning: pango_context_set_font_description: assertion 'context != NULL' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: PangoWarning: pango_context_set_base_dir: assertion 'context != NULL' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: PangoWarning: pango_context_set_language: assertion 'context != NULL' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: PangoWarning: pango_layout_new: assertion 'context != NULL' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: PangoWarning: pango_layout_set_attributes: assertion 'layout != NULL' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: PangoWarning: pango_layout_set_text: assertion 'layout != NULL' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: PangoWarning: pango_layout_get_unknown_glyphs_count: assertion 'PANGO_IS_LAYOUT (layout)' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: GtkWarning: gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(self.gladefile)
window.py:184: GtkWarning: gdk_colormap_alloc_colors: assertion 'GDK_IS_COLORMAP (colormap)' failed
  self.builder.add_from_file(self.gladefile)
Traceback (most recent call last):
  File "window.py", line 1572, in <module>
    wine = oxcWindow()
  File "window.py", line 184, in __init__
    self.builder.add_from_file(self.gladefile)
glib.GError: Could not parse color `#ffff00000000'
Exiting...
