### ISSUE TITLE
openxenmanager should have a .desktop file and icon for better desktop integration

### ISSUE THREAD

**Issue by benwbooth** [OpenXenManager/openxenmanager#38]
What the title says. Thanks!

**Comment by mprenditore** [comment]
I know that is a old post, but I have created a desktop files for this... Are anyone already interested?
If yes, I'm new to github, so how I can push my changes? I should create a new branch and start a pull request?

**Comment by dlintott** [comment]
Absolutely interested :) 

As you've already got an account on GitHub, you can fork the repository, apply the changes and send a pull request

Forking - https://help.github.com/articles/fork-a-repo
Pull Requests - https://help.github.com/articles/using-pull-requests

**Comment by mprenditore** [comment]
Thank you for your help.
I forked and pushed.
I also made a pull request.

It's in reviewing ;)

**Comment by dlintott** [comment]
@mprenditore Many thanks... I shall take a look at the PR later and merge it  in

**Comment by mprenditore** [comment]
Perfect... I hope you enjoy!

**Comment by mprenditore** [comment]
@dlintott did you check the PR?

**Comment by mprenditore** [comment]
up

**Comment by dlintott** [comment]
Finally got around to merging this in.... Better late than never!
