### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by noiala** [OpenXenManager/openxenmanager#54]
Hi,
I'm trying to connect to my local server using openxenmanager but I'm getting a connection refused.
The application launches just fine but it fails when I try to add a new server. Firewall is all off and I also double checked credentials. 
The manager is installed in the same machine where Xen is running.
Thanks!

**Comment by dlintott** [comment]
You mention openxenmanager is installed on the same machine. Are you definitely running either XenServer (I guess not as this doesn't have a GUI at all) or XCP (Deprecated).

OpenXenManager won't work with the older Xen Hypervisor that was previously available through distro's such as Debian (https://tracker.debian.org/pkg/xen)

**Comment by noiala** [comment]
Thx for the reply. I got it working. You are correct. There were some issues during the xcp-api installation. I'm running Xen Hypervisor + OpenXenManager. I was switching between toolstacks xapi | xl for testing purposes..so at the end my setup works ok (of course only if the toolstack is set to xl)

**Comment by dlintott** [comment]
Excellent, I'm glad to hear you got it working. Please feel free to file bug reports against OpenXenManager for any bugs you find.
