### ISSUE TITLE
set_style error

### ISSUE THREAD

**Issue by kalimalrazif** [OpenXenManager/openxenmanager#66]
Good day:

I tried to run the program but the following message appears, any thoughs about? Thanks in advance

```
python2 window.py 
window.py:194: GtkWarning: Ignoring the separator setting
  self.builder.add_from_file(self.gladefile)
window.py:194: GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  self.builder.add_from_file(self.gladefile)
Traceback (most recent call last):
  File "window.py", line 1759, in <module>
    wine = oxcWindow()
  File "window.py", line 281, in __init__
    self.builder.get_object("checksetsyle").set_active(self.config["gui"]["set_style"] == "True")
  File "/home/nomar/bin/openxenmanager/configobj.py", line 567, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'set_style'
Exiting...
```

**Comment by dlintott** [comment]
Hi,

I can't actually work out why it is looking for that value there! 

I would suggest deleting or renaming the config file (~/.config/openxenmanager/oxc.conf) and trying again.

**Comment by kalimalrazif** [comment]
Thanks :-D I will do so ;-)


[image: --]

Nomar Mora
[image: http://]about.me/nomar.mora
<http://about.me/nomar.mora?promo=email_sig>

**Comment by dcbeckett** [comment]
I had the same issue with two different ubuntu machines im working on, issue could be due to me installing openxenmanager from the repos first, before downloading it directly from sourceforge, may be a conflict between the two software's configs?

Deleting the conf file fixed the issue

**Comment by garuhhh** [comment]
yeah.. renaming oxc.conf fixed it for me as well. Like dcbeckett, I installed openxenmanager from ubuntu repos first before downloading it directly from sourceforge.

**Comment by dlintott** [comment]
Okay, thanks to @garuhhh I've tracked down where the issue is!

All references to checksetsyle/set_style were removed in rev 66 & 67. Ubuntu's version is based on rev 80, so doesn't know what to do with this checksetsyle/set_style.

https://sourceforge.net/p/openxenmanager/code/66/tree//trunk/window.py?diff=5176cecc34309d5bc6065087:65

This should be handled in the code, so ensure this doesn't happen (I shall also remove the rev 48 download from sourceforge)

**Comment by dlintott** [comment]
After thinking about this... I can't fix this for in the code for old versions (duh... can't go back in time!)

So I have restructured the sourceforge project and added README files to make it clear that the versions hosted there are going to be full of bugs! :bug: 

Thankyou to everyone for reporting the issue... and helping me find the reason why!
