### ISSUE TITLE
KeyError: 'set_style'

### ISSUE THREAD

**Issue by garuhhh** [OpenXenManager/openxenmanager#74]
openxenmanager doesn't open from mine (Ubuntu 15.04 64bit). 
edit: I downloaded the tar openxenmanager_rev48.tar.gz from sourceforge

Here is the output from terminal:

```
ubuntu@ubuntu:~/Downloads/applications/openxenmanager$ python window.py
window.py:194: GtkWarning: Ignoring the separator setting
  self.builder.add_from_file(self.gladefile)
window.py:194: GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  self.builder.add_from_file(self.gladefile)
Traceback (most recent call last):
  File "window.py", line 1759, in <module>
    wine = oxcWindow()
  File "window.py", line 281, in __init__
    self.builder.get_object("checksetsyle").set_active(self.config["gui"]["set_style"] == "True")
  File "/home/ubuntu/Downloads/applications/openxenmanager/configobj.py", line 567, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'set_style'
Exiting...
```

**Comment by dlintott** [comment]
Hi,

This is a puzzling bug (as you aren't the first to experiance it!)

1. Is this a fresh install?
2. Could you post the content of /home/ubuntu/.config/openxenmanager/oxc.conf

Thanks

**Comment by garuhhh** [comment]
Hi! Here is the content of oxc.conf:

[gui]
show_xs_templates = True
show_custom_templates = True
show_local_storage = True
show_toolbar = True
save_password = False
master_password = ""
show_hidden_vms = False
[servers]
[[hosts]]
192.168.1.24 = root, "", False
[maps]
check_unused_network = False
check_unused_storage = False
check_show_storage = True
check_show_network = True
check_show_halted_vms = False

**Comment by garuhhh** [comment]
Hi again,

Found this issue just now (it didn't show up during my googling):
https://github.com/OpenXenManager/openxenmanager/issues/66

it asked to rename oxc.conf, tried it, and openxenmanager opened successfully!

**Comment by dlintott** [comment]
Indeed, that is the same issue... I'm currently puzzled as to why the error occurs in the first place.

Was it working previously?
Did you do nay thing particualr before the error?

**Comment by garuhhh** [comment]
nope. didn't do anything, except to install openxenmanager from ubuntu repos. Must be a conflict with the confs from the repo and the one from sourceforge?

**Comment by dlintott** [comment]
Okay... Just seen the edit to your first post... That gives me something to work with!

I shall attempt to reproduce and catch the error

**Comment by garuhhh** [comment]
thanks for the work! :)
