### ISSUE TITLE
menu bar inaccessible in Ubuntu (15.04) Vivid 

### ISSUE THREAD

**Issue by garuhhh** [OpenXenManager/openxenmanager#75]
The menu bar is inaccessible in Ubuntu Vivid. I have enabled Local Menus, so I have them on other windows, but not in Openxenmanager.

![image](https://cloud.githubusercontent.com/assets/1308747/7384710/1d252d64-ee6b-11e4-9522-c66353f66926.png)

edit: see the menus in the terminal, no menus in openxenmanager even if i hover the mouse on the title bar.

**Comment by dlintott** [comment]
Are you using the latest source or the version from Ubuntu? 

This was fixed for Trusty in #11

**Comment by dlintott** [comment]
More specifically fied in PR #35 and commit https://github.com/OpenXenManager/openxenmanager/commit/9cf7b4cc7d69c4bab93c52d23b4efa9317b48f2e

**Comment by garuhhh** [comment]
I'm using Ubuntu 15.04 Vivid, and tried both the one from ubuntu source and from sourceforge (before the link was taken down). Both of them shows this issue.

I'm not able to open the one I pulled from git. I filed an issue for it:
https://github.com/OpenXenManager/openxenmanager/issues/76

Thanks @dlintott !

**Comment by garuhhh** [comment]
I was able to run the most recent pull from git, thanks to @dlintott .

However, still no menus :(

![screenshot from 2015-04-29 09 22 29](https://cloud.githubusercontent.com/assets/1308747/7409087/0ef96c28-ef56-11e4-98c9-85721ef4f810.png)
