### ISSUE TITLE
ImportError: No module named configobj

### ISSUE THREAD

**Issue by garuhhh** [OpenXenManager/openxenmanager#76]
I cloned the source from git, then run the openxenmanager script. Here is what I got from the terminal:

    ubuntu@ubuntu:~/Downloads/source/myopenxenmanager$ ./openxenmanager 
    Traceback (most recent call last):
      File "./openxenmanager", line 30, in <module>
        from OXM.window import oxcWindow
      File "./src/OXM/window.py", line 25, in <module>
        from configobj import ConfigObj
    ImportError: No module named configobj

I'm using Ubuntu Vivid 15.04, 64bit. Anything else I can provide?

**Comment by dlintott** [comment]
Ah, yes... I must make this clearer in the README. 

You need to install configobj:

```sudo apt-get install python-configobj```

That should work on Debian or Ubuntu

**Comment by garuhhh** [comment]
Thanks @dlintott ! it's running now :)

yeah, putting that in README would be helpful :+1:
