### ISSUE TITLE
Add Server with button in "Home" Tab didn't work

### ISSUE THREAD

**Issue by davidak** [OpenXenManager/openxenmanager#79]
console output:

```
Traceback (most recent call last):
  File "./src/OXM/window_menuitem.py", line 358, in on_tb_addserver_clicked
    AddServer(self.builder)
  File "./src/OXM/window_addserver.py", line 38, in __init__
    self.builder = main.builder
AttributeError: 'gtk.Builder' object has no attribute 'builder'
```

Via Menu: Server -> Add... works

---

Elementary OS Freya (Ubuntu 14.04 LTS based)
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
>>> import gtk
>>> gtk.gtk_version
(2, 24, 23)
>>> gtk.pygtk_version
(2, 24, 0)

**Comment by Dark-Fx** [comment]
I'm getting this as well on both OSX and Debian Jessie.

**Comment by dlintott** [comment]
Doh... I reworked the add server box... Obviously forget to change that bit to the new version. 

As soon as I manage to get my PC working again I'll get on it

**Comment by iTech278** [comment]
Hello! Any update on this? Thanks :)

**Comment by dlintott** [comment]
No update as such... I just need to find time in between work and sorting out life!

It'll be sorted soon enough

**Comment by iTech278** [comment]
No problem at all, just asking out of curiosity. :)

**Comment by davidak** [comment]
It works now (tested on OS X).

Thank You!
