### ISSUE TITLE
Can't start openxencenter on fedora 22!

### ISSUE THREAD

**Issue by giumbai** [OpenXenManager/openxenmanager#82]
$ ./openxenmanager
Traceback (most recent call last):
  File "./openxenmanager", line 30, in <module>
    from OXM.window import oxcWindow
  File "./src/OXM/window.py", line 25, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj
This is what i get, i'm on fedora 22, python 2.7.10, i have both python vnc and pygtk installed i've installed even the devel packages ...

**Comment by dlintott** [comment]
You need to install the ConfigObj package... Either from your distribution or using pip
