### ISSUE TITLE
Internal network Interface missing

### ISSUE THREAD

**Issue by seijikun** [OpenXenManager/openxenmanager#99]
The network interfaces of our XenServer (6.5.0):
*Host internal management Network (___xenapi___)
*External (___xenbr0___)
*Management (___xenbr1___)
*VM Intern (___xapi0___)

OpenXenManager does only show the first 3 in all dialogs, whereas only the last 3 are networks that we created.
Are the checks that hide "xapi0" deprecated?

**Comment by dlintott** [comment]
I believe the issue you are experiencing was fixed some time ago in commit https://github.com/OpenXenManager/openxenmanager/commit/898053c085f4d6f3399473459e7b2c80fdbb2aca.

Could you ensure you're running the latest version of code from here (not the last release) and see if that fixes the problem.
